package com.angryguyy.metadatastripper.listeners;

import org.bukkit.Location;
import org.bukkit.entity.Player;
import org.bukkit.event.EventHandler;
import org.bukkit.event.EventPriority;
import org.bukkit.event.Listener;
import org.bukkit.event.player.PlayerJoinEvent;
import org.bukkit.event.player.PlayerMoveEvent;
import org.bukkit.event.player.PlayerQuitEvent;
import org.bukkit.util.Vector;

import com.angryguyy.metadatastripper.MetadataStripper;
import com.angryguyy.metadatastripper.data.PlayerData;
import com.angryguyy.metadatastripper.data.VectorialLocation;
import com.angryguyy.metadatastripper.tasks.RayTraceCallable;
import com.angryguyy.metadatastripper.tasks.UpdateBukkitRunnable;

/**
 * Listens for player lifecycle and movement events to manage their asynchronous ray-tracing profiles.
 * <p>
 * This class ensures that the Ray-Tracer always has the most up-to-date mathematical
 * coordinates (eye location and directional vectors) for every active player.
 */
public final class PlayerListener implements Listener {

    private final MetadataStripper plugin;

    /**
     * Constructs the PlayerListener.
     *
     * @param plugin the main plugin instance.
     */
    public PlayerListener(MetadataStripper plugin) {
        this.plugin = plugin;
    }

    /**
     * Initializes the player's secure data profile and binds the async RayTraceCallable
     * when they join the server.
     */
    @EventHandler
    public void onPlayerJoin(PlayerJoinEvent event) {
        Player player = event.getPlayer();

        // Validates if the player is a real entity (e.g., ignores Citizens NPCs)
        if (!plugin.validatePlayer(player)) return;

        // Create the initial snapshot of the player's eye location
        PlayerData playerData = new PlayerData(
                MetadataStripper.getLocations(player, new VectorialLocation(player.getEyeLocation()))
        );

        // Bind the asynchronous ray-tracing worker to this player's data profile
        playerData.setCallable(new RayTraceCallable(plugin, playerData));
        plugin.getPlayerData().put(player.getUniqueId(), playerData);

        // Folia compatibility: schedule the ticking task on the specific player's regional thread
        if (plugin.isFolia()) {
            player.getScheduler().runAtFixedRate(
                    plugin,
                    new UpdateBukkitRunnable(plugin, player),
                    null,
                    1L,
                    plugin.getUpdateTicks()
            );
        }
    }

    /**
     * Cleans up the player's data profile to prevent memory leaks when they leave the server.
     */
    @EventHandler
    public void onPlayerQuit(PlayerQuitEvent event) {
        plugin.getPlayerData().remove(event.getPlayer().getUniqueId());
    }

    /**
     * Captures the player's real-time spatial and directional data.
     * <p>
     * Performance: Implements a strict delta-check to discard redundant "spam" movement packets
     * generated by the client, preventing massive Garbage Collection overhead.
     */
    @EventHandler(priority = EventPriority.MONITOR, ignoreCancelled = true)
    public void onPlayerMove(PlayerMoveEvent event) {
        Location from = event.getFrom();
        Location to = event.getTo();

        // Safety check and Delta-Check: Discard redundant packet spam where the player didn't actually move or rotate
        if (to == null || (from.getX() == to.getX()
                && from.getY() == to.getY()
                && from.getZ() == to.getZ()
                && from.getYaw() == to.getYaw()
                && from.getPitch() == to.getPitch())) {
            return;
        }

        Player player = event.getPlayer();
        PlayerData playerData = plugin.getPlayerData().get(player.getUniqueId());

        if (!plugin.validatePlayerData(player, playerData, "onPlayerMove")) return;

        // Verify the player hasn't switched worlds mid-tick
        if (to.getWorld().equals(playerData.getLocations()[0].getWorld())) {

            // Translate foot location to eye location asynchronously
            VectorialLocation location = new VectorialLocation(to);
            Vector vector = location.getVector();
            vector.setY(vector.getY() + player.getEyeHeight());

            // Push the immutable snapshot to the volatile array (Thread-Safe handoff)
            playerData.setLocations(MetadataStripper.getLocations(player, location));
        }
    }
}