name: Paper compatibility

on:
  push:
  pull_request:

jobs:
  compile:
    name: Paper ${{ matrix.paper_version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        paper_version:
          - 1.21-R0.1-SNAPSHOT
          - 1.21.1-R0.1-SNAPSHOT
          - 1.21.3-R0.1-SNAPSHOT
          - 1.21.4-R0.1-SNAPSHOT
          - 1.21.5-R0.1-SNAPSHOT
          - 1.21.6-R0.1-SNAPSHOT
          - 1.21.7-R0.1-SNAPSHOT
          - 1.21.8-R0.1-SNAPSHOT
          - 1.21.9-R0.1-SNAPSHOT
          - 1.21.10-R0.1-SNAPSHOT
          - 1.21.11-R0.1-SNAPSHOT
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Compile target
        run: ./gradlew clean test compileJava "-PpaperVersion=${{ matrix.paper_version }}"